// export { default as ExitQueue } from "./ExitQueue.json";
export { default as Fruit } from "./Fruit.json";
// export { default as LockedFruit } from "./LockedFruit.json";
export { default as Presale } from "./Presale.json";
// export { default as PresaleAllocation } from "./PresaleAllocation.json";
export { default as StableCoin } from "./StableCoin.json";
export { default as EarthERC20Token } from "./EarthERC20Token.json";
export { default as EarthStaking } from "./EarthStaking.json";
export { default as EarthTreasury } from "./EarthTreasury.json";
// export { default as Nft } from "./Nft.json";
export { default as Claim } from "./claim.json";
